CREATE TABLE IF NOT EXISTS employee
(
    id                INTEGER        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surname           VARCHAR(64)    NOT NULL,
    name              VARCHAR(64)    NOT NULL,
    gender            VARCHAR(6)     NOT NULL,
    position          VARCHAR(96)    NOT NULL,
    department        VARCHAR(96)    NOT NULL,
    email             VARCHAR(64)    NOT NULL,
    salary            DECIMAL(19, 4) NOT NULL,
    birth_date        DATE           NOT NULL,
    education         VARCHAR(16)    NOT NULL,
    employment_status VARCHAR(16)    NOT NULL
)