CREATE TABLE IF NOT EXISTS salary_range
(
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    position   VARCHAR        NOT NULL,
    min_salary DECIMAL(19, 4) NOT NULL,
    max_salary DECIMAL(19, 4) NOT NULL
)