CREATE TABLE IF NOT EXISTS engineer
(
    id                   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_id          INTEGER NOT NULL REFERENCES employee (id) ON DELETE CASCADE,
    programming_language VARCHAR,
    tool                 VARCHAR,
    certification        VARCHAR
)