CREATE TABLE IF NOT EXISTS analyst
(
    id                               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_id                      INTEGER NOT NULL REFERENCES employee (id) ON DELETE CASCADE,
    notation                         VARCHAR,
    business_domain                  VARCHAR,
    requirements_gathering_technique VARCHAR
)