CREATE TABLE IF NOT EXISTS developer
(
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_id     INTEGER NOT NULL REFERENCES employee (id) ON DELETE CASCADE,
    framework       VARCHAR,
    database_skill  VARCHAR,
    version_control VARCHAR
)