CREATE TABLE IF NOT EXISTS manager
(
    id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_id    INTEGER NOT NULL REFERENCES employee (id) ON DELETE CASCADE,
    department     VARCHAR,
    responsibility VARCHAR
)